"""expand users and add user_settings

Revision ID: 7bdacbea490e
Revises: 09774758d188
Create Date: 2026-05-05 13:58:59.569302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bdacbea490e'
down_revision: Union[str, Sequence[str], None] = '09774758d188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_max_per_day', sa.Integer(), server_default='5', nullable=False),
    sa.Column('stress_threshold', sa.Float(), server_default='0.75', nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), server_default='22:00', nullable=False),
    sa.Column('quiet_hours_end', sa.Time(), server_default='08:00', nullable=False),
    sa.Column('silence_during_meeting', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('silence_during_exercise', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('consent_audit_logging', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('language', sa.String(length=8), server_default='ko', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('supabase_user_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('anon_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=16), server_default='user', nullable=False))
    op.add_column('users', sa.Column('consent_raw_biosignals', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('consent_revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_anon_id'), 'users', ['anon_id'], unique=True)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_anon_id'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'consent_revoked_at')
    op.drop_column('users', 'consent_raw_biosignals')
    op.drop_column('users', 'role')
    op.drop_column('users', 'anon_id')
    op.drop_column('users', 'supabase_user_id')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
